<?php

namespace Location\PlanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findAllOrderedByFrom()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM LocationPlanBundle:Event e ORDER BY e.from ASC'
            )
            ->getResult();
    }
}
