<?php

namespace Location\PlanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findAllOrderedByFrom()
    {
        return $this->createQueryBuilder('e')
         ->orderBy('e.from', 'ASC')
         ->getQuery()
         ->getResult();
    }
}
