<?php

namespace Location\PlanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends EntityRepository
{
    public function findAllOrderedByNumber()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM LocationPlanBundle:Room r ORDER BY r.number ASC'
            )
            ->getResult();
    }
}
