<?php

namespace Location\PlanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends EntityRepository
{
    public function findAllOrderedByNumber()
    {
        return $this->createQueryBuilder('r')
         ->orderBy('r.number', 'ASC')
         ->getQuery()
         ->getResult();
    }
}
