security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        login_firewall:
            pattern: ^/login$
            anonymous: ~

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
            #    login_path: login
            #    check_path: login_check
                always_use_default_target_path: true
            #    default_target_path: /
            logout: ~
            #    path:   _demo_logout
            #    target: _demo

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin$, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
