TouchMe\FloorPlanBundle\Entity\Asset:
  type: entity
  table: asset
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      length: 255
      nullable: false
    src:
      type: string
      length: 255
      nullable: false
    #file:
      #- File:
        #maxSize: 20M
  manyToMany:
    events:
      targetEntity: Event
      mappedBy: assets
      nullable: false
  lifecycleCallbacks:
    prePersist: [preUpload]
    preUpdate: [preUpload]
    postPersist: [upload]
    postUpdate: [upload]
    postRemove: [removeUpload]