TouchMe\FloorPlanBundle\Entity\Event:
  type: entity
  repositoryClass: TouchMe\FloorPlanBundle\Entity\EventRepository
  table: event
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      length: 255
    starttime:
      type: datetime
    endtime:
      type: datetime
    description:
      type: text
    branchofstudy:
      type: string
      length: 100
    personincharge:
      type: string
      length: 100
  manyToOne:
    location:
      targetEntity: Location
      inversedBy: events
  manyToMany:
    assets:
      targetEntity: Asset
      inversedBy: events