TouchMe\FloorPlanBundle\Entity\Event:
  type: entity
  repositoryClass: TouchMe\FloorPlanBundle\Entity\EventRepository
  table: event
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      length: 255
      nullable: false
    startdate:
      type: string
      length: 255
      nullable: false
    starttime:
      type: string
      length: 255
      nullable: false
    enddate:
      type: string
      length: 255
      nullable: false
    endtime:
      type: string
      length: 255
      nullable: false
    description:
      type: text
      nullable: true
    branchofstudy:
      type: string
      length: 100
      nullable: false
    personincharge:
      type: string
      length: 100
      nullable: false
  manyToOne:
    location:
      targetEntity: Location
      inversedBy: events
      nullable: false
  manyToMany:
    assets:
      targetEntity: Asset
      inversedBy: events
      nullable: true
