<?php

namespace TouchMe\FloorPlanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
  public function findAllOrderedByStarttime()
  {
    return $this->createQueryBuilder('e')->orderBy('e.starttime', 'ASC')->getQuery()->getResult();
  }
}
