<?php

namespace TouchMe\FloorPlanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
  public function findAllOrderedByNumber()
  {
    return $this->createQueryBuilder('l')->orderBy('l.number', 'ASC')->getQuery()->getResult();
  }
  
  public function findAllExept($param)
  {
    $qb = $this->createQueryBuilder('l');
    $qb->select('l')
      ->where($qb->expr()->notIn('l.id', '?1'))
      ->setParameter(1, $param);
    
    return $qb->getQuery()->getResult();
  }
}
