location:
  pattern: /admin/location/
  defaults: { _controller: TouchMeFloorPlanBundle:Location:index }

location_new:
  pattern: /admin/location/new
  defaults: { _controller: TouchMeFloorPlanBundle:Location:new }

location_create:
  pattern: /admin/location/create
  defaults: { _controller: TouchMeFloorPlanBundle:Location:create }

location_edit:
  pattern: /admin/location/edit/{id}
  defaults: { _controller: TouchMeFloorPlanBundle:Location:edit }

location_save:
  pattern: /admin/location/save/{id}
  defaults: { _controller: TouchMeFloorPlanBundle:Location:save }

location_remove:
  pattern: /admin/location/remove/{id}
  defaults: { _controller: TouchMeFloorPlanBundle:Location:remove }

event:
  pattern: /admin/event/
  defaults: { _controller: TouchMeFloorPlanBundle:Event:index }

export:
  pattern: /admin/export/
  defaults: { _controller: TouchMeFloorPlanBundle:Export:index }

import:
  pattern: /admin/import/
  defaults: { _controller: TouchMeFloorPlanBundle:Import:index }

touch_me_floor_plan_homepage:
  pattern:  /{name}
  defaults: { _controller: TouchMeFloorPlanBundle:Default:index, name: home}