room:
  pattern: /room/{name}
  defaults: { _controller: TouchMeFloorPlanBundle:Room:index, name: room }

event:
  pattern: /event/{name}
  defaults: { _controller: TouchMeFloorPlanBundle:Event:index, name: event }

touch_me_floor_plan_homepage:
  pattern:  /{name}
  defaults: { _controller: TouchMeFloorPlanBundle:Default:index, name: home}