TouchMe\FloorPlanBundle\Entity\Event:
  properties:
    title:
      - NotBlank: ~
    starttime:
      - NotNull: ~
    endtime:
      - NotNull: ~
    branchofstudy:
      - NotBlank: ~
    personincharge:
      - NotBlank: ~
    location:
      - NotNull: ~

TouchMe\FloorPlanBundle\Entity\Location:
  properties:
    number:
      - NotBlank: ~
    type:
      - NotBlank: ~

TouchMe\FloorPlanBundle\Entity\Asset:
  properties:
    title:
      - NotBlank: ~